using System.IO;

namespace Flexy.AssetRefs
{
	public abstract class ContentService : MonoBehaviour
	{
		[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
		private static	void	Bootstrap	( )		
		{
			SpawnContentService();
		}
	
		private const	String	PrefabResourcePath			= "Fun.Flexy/ContentServiceRef";
		private const	String	PrefabResourceDirectory		= "Assets/Resources/Fun.Flexy";
		private const	String	PrefabResourceAssetPath		= PrefabResourceDirectory + "/ContentServiceRef.asset";

		private static		void	SpawnContentService		( )	
		{
			GameObject? prefab = null;
		
			var serviceRef = Resources.Load<ResourceRef>(PrefabResourcePath);
			if (serviceRef)
			{
				prefab = serviceRef.Ref as GameObject;
				if (prefab == null)
				{
					Debug.LogError($"Resource reference '{PrefabResourcePath}' does not point to a GameObject prefab.");
					prefab = null;
				}
				else
				{
					var service = prefab.GetComponent<ContentService>();
					if (!service)
					{
						Debug.LogError($"Service prefab referenced by '{PrefabResourcePath}' has no {nameof(ContentService)} component.");
						prefab = null;
					}
				}
			}

			GameObject serviceObject;
		
			if (prefab != null)
			{
				var prefabWasActive = prefab.gameObject.activeSelf;

				try
				{
					prefab.SetActive(false);
					serviceObject = Instantiate(prefab);
				}
				finally
				{
					prefab.SetActive(prefabWasActive);
					
					#if UNITY_EDITOR
					if (prefab && !prefab.scene.IsValid() && !String.IsNullOrEmpty(UnityEditor.AssetDatabase.GetAssetPath(prefab)))
						UnityEditor.EditorUtility.ClearDirty(prefab);
					#endif
				}
			}
			else
			{
				serviceObject = new GameObject("ContentService_AutoGenerated");
				serviceObject.SetActive(false);
				serviceObject.AddComponent<ContentService_Resources>();
			}
			
			DontDestroyOnLoad(serviceObject);
			serviceObject.SetActive(true);
		}
		protected virtual	void	Awake					( ) { Ref = this; }
		protected virtual	void	OnDestroy				( ) { Ref = null!; }
	
		public static	ContentService	Ref {get; private set;} = null!;

		public abstract	T?				LoadAssetSync<T>	( AssetRef @ref ) where T : Object;
		public abstract	UniTask<T?>		LoadAssetAsync<T>	( AssetRef @ref ) where T : Object;
		public abstract	void			UnloadAsset<T>		( AssetRef @ref ) where T : Object;
			
		public abstract	String			GetSceneName		( SceneRef @ref );
		public abstract	LoadSceneTask	LoadSceneAsync		( SceneRef @ref, LoadSceneTask.Parameters p, GameObject context );
		public virtual	LoadSceneTask	LoadDummyScene		( GameObject ctx, LoadSceneMode mode, UnloadSceneOptions unloadOptions, Action? createSceneObjects, params Type[] components )
		{
			var sceneTask			= new LoadSceneTask(ctx, default, new LoadSceneTask.Parameters(mode));

			return sceneTask.Run( LoadDummyScene_Internal( sceneTask, mode, unloadOptions, createSceneObjects, components ) );
			
			static async UniTask<Scene>  LoadDummyScene_Internal( LoadSceneTask sceneTask, LoadSceneMode mode, UnloadSceneOptions unloadOptions, Action? createSceneObjects, params Type[] components )
			{
				List<Scene>?	scenesToUnload	= null; 
					
				if (mode == LoadSceneMode.Single)
				{
					scenesToUnload = new();
					var count = SceneManager.loadedSceneCount;
					for (var i = count - 1; i >= 0; i--)
						scenesToUnload.Add( SceneManager.GetSceneAt(i) );
				}
			
				var dummySceneName = "Dummy";
				
				while(true)
				{
					var existingDummy = SceneManager.GetSceneByName(dummySceneName);
					if (!existingDummy.IsValid())
						break;
					
					dummySceneName += "2";
				}
			
				var dummy	= SceneManager.CreateScene(dummySceneName);
				sceneTask.Scene	= dummy;
				
				await UniTask.NextFrame();
			
				SceneManager.SetActiveScene(dummy);
			
				var dummyObj = new GameObject( "DummyObj", components );
			
	#if UNITY_URP
				var hasCam = ((IList<Type>)components).Contains(typeof(Camera));
				if (hasCam)
					dummyObj.AddComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>();
	#elif UNITY_HDRP
				var hasCam = components.Contains(typeof(Camera));
				if (hasCam)
					dummyObj.AddComponent<UnityEngine.Rendering.HighDefinition.HDAdditionalCameraData>();
	#endif
			
				if ( createSceneObjects != null)
				{
					try						{ createSceneObjects(); }
					catch (Exception ex)	{ Debug.LogException(ex); }
				}
			
				sceneTask.StepProgress = 0.9f;
					
				if (scenesToUnload != null)
				{
					foreach (var scn in scenesToUnload)
						if (scn.IsValid())
							await SceneManager.UnloadSceneAsync( scn, unloadOptions ).ToUniTask();
				}
			
				sceneTask.StepProgress = 1f;
				
				return dummy;
			}
		}

		public static			T?				GetSpecializedAsset<T>	( Object? asset ) where T : Object				
		{
			if (asset is GameObject go && typeof(T).IsSubclassOf(typeof(Component)))
				return go.GetComponent<T>();

			return asset as T;
		}
		public static async		UniTask<Scene>	WaitSceneLoad			( AsyncOperation ao, LoadSceneTask sceneTask )	
		{
			ao.allowSceneActivation	= sceneTask.Params.AllowActivation;
			ao.priority				= sceneTask.Params.Priority;
	
			while ( !ao.isDone && ( ao.allowSceneActivation || ao.progress < 0.9f ) )
			{
				await UniTask.NextFrame();
				sceneTask.StepProgress = ao.progress;
			}
				
			sceneTask.StepProgress = 0.9f;
		
			if (!ao.allowSceneActivation)
			{
				while (sceneTask.DelaySceneActivation)
					await UniTask.NextFrame();

				ao.allowSceneActivation = true;
				await UniTask.NextFrame( );
			}
		
			while (ao.progress < 1.0f)
			{
				sceneTask.StepProgress = ao.progress;
				await UniTask.NextFrame();
			}
		
			return sceneTask.Scene;
		}
		
#if UNITY_EDITOR
		public static void EditorSetupContentServiceResourceRef( ContentService servicePrefab )
		{
			if (!servicePrefab)
				throw new UnityEditor.Build.BuildFailedException($"{nameof(ContentService)} prefab reference is not assigned.");

			Directory.CreateDirectory(PrefabResourceDirectory);

			var resourceRef = UnityEditor.AssetDatabase.LoadAssetAtPath<ResourceRef>(PrefabResourceAssetPath);
			if (!resourceRef)
			{
				if (UnityEditor.AssetDatabase.LoadMainAssetAtPath(PrefabResourceAssetPath))
					throw new UnityEditor.Build.BuildFailedException($"Asset '{PrefabResourceAssetPath}' exists but is not a {nameof(AssetLoaders.ResourceRef)}.");

				resourceRef = ScriptableObject.CreateInstance<ResourceRef>();
				UnityEditor.AssetDatabase.CreateAsset(resourceRef, PrefabResourceAssetPath);
			}

			resourceRef.Name	= String.Empty;
			resourceRef.Ref		= servicePrefab.gameObject;

			UnityEditor.EditorUtility.SetDirty(resourceRef);
			UnityEditor.AssetDatabase.SaveAssets();
			UnityEditor.AssetDatabase.ImportAsset(PrefabResourceAssetPath, UnityEditor.ImportAssetOptions.ForceSynchronousImport);
		}
#endif
	}
}
